// [waktu_dalam_detik, "Lirik"]
const lyrics = [
  [33, "Nama yang sama\nbertahan"],
  [38, "Dalam ruangan hening"],
  [42, "Tanpa suara\nbertahan"],
  [46, "Tak bergeming"],
  [50, "Terlalu lama\nbercanda"],
  [55, "Kita tak terbiasa"],
  [58, "Dengan celaka\nyang nyata"],
  [63, "Diam tak berdaya"],
  [67, "Namun\naku bingung\nkenapa ku tak pergi"],
  [72, "Aku bingung\nkalian masih di sini"],
  [76, "Apa mungkin karena terlalu lama"],
  [80, "Apa benar tuk berbagi derita"],
  [85, "Mungkin nanti\nsemua justru memburuk"],
  [89, "Hati-hati\nnamun terjatuh lagi"],
  [93, "Tapi luka adalah niscaya"],
  [97, "Kutanggung denganmu\nselama ku mampu"],
  [104, "Selama ku mampu"],
  [117, "Di kehidupan kedua"],
  [122, "Semoga kau tak terlalu keras kepala"],
  [125, "Atau mungkin ini bukan yang pertama"],
  [129, "Dan kita diberi kesempatan berubah"],
  [133, "Kuyakin nyawa kita bertautan"],
  [139, "Khatam berbagai cobaan"],
  [142, "Selalu menertawakan ramalan bintang kartu tarot"],
  [147, "Orang pintar pembaca nasib"],
  [151, "Namun aku bingung\nkenapa ku tak pergi"],
  [155, "Aku bingung kalian masih di sini"],
  [160, "Apa mungkin karena terlalu lama"],
  [165, "Apa benar tuk berbagi derita"],
  [168, "Mungkin nanti\nsemua justru memburuk"],
  [172, "Hati-hati\nnamun terjatuh lagi"],
  [177, "Tapi luka adalah niscaya"],
  [180, "Kutanggung denganmu\nselama ku mampu"],
  [187, "Selama ku mampu"],
  [192, "Selalu menertawakan ramalan bintang kartu tarot"],
  [197, "Orang pintar pembaca nasib\nnamun"],
  [203, "Padamu kupercaya"],
  [212, "Tak masuk logika"],
  [220, "Padamu kupercaya"],
  [228, "Tak masuk logika"],
  [236, "Padamu kupercaya"],
  [244, "Tak masuk logika"],
  [254, "Padamu kupercaya"],
  [262, "Tak masuk logika"],
  [270, "Padamu kupercaya"],
  [278, "Tak masuk logika"]
  [280, " "]
];
